#ifndef BASIC_BASICDIALECT_H
#define BASIC_BASICDIALECT_H

#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/IR/Dialect.h"

// we have to manually expose the autogenerated files...
#include "Basic/BasicOpsDialect.h.inc"

#endif
