set autoindent
set expandtab
set mouse=a
set ruler
set softtabstop=2
set shiftwidth=2
set tabstop=2

set term=xterm-256color

filetype plugin on
syntax on

set colorcolumn=80
set number

call plug#begin()
Plug 'rhysd/vim-clang-format'

Plug 'derekwyatt/vim-scala'
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
call plug#end()

" Configuration for vim-scala
au BufRead,BufNewFile *.sbt set filetype=scala
